### ISSUE TITLE
Weights Release

### ISSUE THREAD

**Issue by Y-Haneji** [CaptainCook4D/error_recognition#1]
@rohithpeddi @likhithapal @CaptainCook4D 
Thank you for the great work!

Would you kindly release the weights for the task of _supervised error recognition_?

I understand that the codes are under construction now.
If you prefer to hand the weights to me privately, I will contact your email address on the paper.

**Comment by rohithpeddi** [comment]
HI @Y-Haneji, 

Thank you for your interest in our work. 
We have used mainly Vanilla Transformer Layers and MLP layers for training. 
So, I assume they should be reasonably reproducible using the final code and training. 

Sorry for the delay. 
We shall release the final code and the corresponding weights by Oct 30th. 
We shall also release the additional features extracted from Video Recognition models to train.

**Comment by Y-Haneji** [comment]
@rohithpeddi 
Thank you for the reply!

I'm looking forward to seeing the updated code.

**Comment by iranroman** [comment]
Hello,

Thank you very much for your work. This is a pretty awesome project. 

I'm working on reproducing your results, and it would be great if you can share the weights for the pre-trained model, in order to have a frame of reference. Is there a plan to share the weights of your best model? Could you kindly provide them?

Cheers!

**Comment by shreyazmz** [comment]
> Hello,
> 
> Thank you very much for your work. This is a pretty awesome project.
> 
> I'm working on reproducing your results, and it would be great if you can share the weights for the pre-trained model, in order to have a frame of reference. Is there a plan to share the weights of your best model? Could you kindly provide them?
> 
> Cheers!

Hello! I agree - this is a great project!

It would definitely be helpful if the weights could be shared?

Shreya

**Comment by rohithpeddi** [comment]
Hi,

We used the following to report our results in the paper. 
Please find the checkpoints here: [LINK](https://utdallas.app.box.com/s/uz3s1alrzucz03sleify8kazhuc1ksl3)

------------------------

The folder consists of the following items:
1. Checkpoints are saved after each training epoch during the training of all the methods and their variants.
2. Checkpoints corresponding to the best performance on validation data. 

They are of the format: {task}\_{model}\_{features}\_{split}\_epoch\_{epoch_num}.pt

-----------------------------------

To evaluate these models, please follow the evaluation script [here](https://github.com/CaptainCook4D/error_recognition/blob/35ef284a673230a3df09dd971fc5163414f23b2b/core/evaluate.py#L120).
